driver:
  name: docker
  run_options: >-
    -v //var/run/docker.sock:/var/run/docker.sock
    -v /usr/local/bin/docker:/bin/docker
    -v <%= ENV['PWD'] %>/repo:/home/kitchen/repo
  #socket: unix:///var/run/docker.sock
  #socket: tcp://localhost:2375
  socket: npipe:////./pipe/docker_engine


provisioner:
  name: ansible_playbook
  chef_bootstrap_url: nil
  hosts: ansible-controller
  playbook: site.yml

platforms:
  - name: centos-7

suites:
  - name: ansible-controller

