- hosts: all
  gather_facts: false
  become: true
  become_user: kitchen
  tasks:
  - name: install the chef-workstation rpm from a remote repo
    become_user: root
    yum:
      name: https://packages.chef.io/files/stable/chef-workstation/0.11.21/el/7/chef-workstation-0.11.21-1.el7.x86_64.rpm

  - name: add 'eval "$(chef shell-init bash)"' to ~/.bash_profile
    lineinfile:
      dest: ~/.bash_profile
      line: eval "$(chef shell-init bash)"

  - name: gem install
    shell: |
      set -e
      . ~/.bash_profile
      gem install kitchen-ansiblepush
      gem install kitchen-docker
